# The URL the site will be built for
base_url = "https://manderley.es"
title = "Manderley"
default_language = "en"

# SASS

compile_sass = false

# TAXONOMIES

taxonomies = [
    { name = "tags", paginate_by = 10, feed = true },
]

# SEARCH INDEX

build_search_index = true

# MARKDOWN

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
nav_items = [
    { name = "Blog", url = "/blog" },
    { name = "About", url = "/about" },
    { name = "Contact", url = "/contact" }
]
# nav_footer = [
#    { name = "RSS", url = "/rss.xml" },
#    { name = "Privacy", url = "/privacy" },
#    { name = "About", url = "/about" }
#]